// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJXd1CdZHKdmgCqZZagZmtNfe6D0uoCQ',
    appId: '1:651958612479:web:87896707ff0faabc3437ca',
    messagingSenderId: '651958612479',
    projectId: 'authtutorial-3cb10',
    authDomain: 'authtutorial-3cb10.firebaseapp.com',
    storageBucket: 'authtutorial-3cb10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqSqo-Q6ze0NfqbLLQsyP7MUqAoaVwV8',
    appId: '1:651958612479:android:52c2021616060ff03437ca',
    messagingSenderId: '651958612479',
    projectId: 'authtutorial-3cb10',
    storageBucket: 'authtutorial-3cb10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlY9KiUbZRYp6BzFWRP6ZrJvzHwD-Wq2k',
    appId: '1:651958612479:ios:09b17e4cb15187803437ca',
    messagingSenderId: '651958612479',
    projectId: 'authtutorial-3cb10',
    storageBucket: 'authtutorial-3cb10.appspot.com',
    iosClientId: '651958612479-hcutcphm8gqh8n7ath4c72uhml8cs22b.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernloginui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlY9KiUbZRYp6BzFWRP6ZrJvzHwD-Wq2k',
    appId: '1:651958612479:ios:09b17e4cb15187803437ca',
    messagingSenderId: '651958612479',
    projectId: 'authtutorial-3cb10',
    storageBucket: 'authtutorial-3cb10.appspot.com',
    iosClientId: '651958612479-hcutcphm8gqh8n7ath4c72uhml8cs22b.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernloginui',
  );
}
